### ISSUE TITLE
インフラストラクチャ構築

### ISSUE THREAD

**Issue by dzeyelid** [lefthandz/demo-github-projects#13]
```[tasklist]
### Tasks
- [ ] https://github.com/lefthandz/demo-github-projects/issues/15
- [ ] https://github.com/lefthandz/demo-github-projects/issues/19
- [ ] https://github.com/lefthandz/demo-github-projects/issues/16
```
